version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.7
    commands:
      - yum install -y https://centos7.iuscommunity.org/ius-release.rpm
      - yum update -y
      - yum install -y python36u python36u-libs python36u-devel python36u-pip
  pre_build:
    commands:
      - pip install dash==1.4.1
      - pip install dash-auth
      - pip install pandas
      - pip install dash-daq==0.2.1
      - pip install numpy
      - pip install plotly_express
      - pip install pickle-mixin
      - pip install datetime
      - pip install pandas-datareader
  build:
    commands:
      - python3 app.py
artifacts:
  files:
    -  README.md
      
